version: '2'

services:
  elasticsearch:
    restart: unless-stopped
    build: compose/elasticsearch/
    volumes:
      - ./compose/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
  
  kibana:
    build: compose/kibana/
    volumes:
      - ./compose/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch