version: '2'

services:
  rabbit:
    restart: unless-stopped
    image: rabbitmq:3.6.11
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=8800
      - RABBITMQ_DEFAULT_PASS=8800pass
      - RABBITMQ_DEFAULT_VHOST=8800vh
    ports:
      - "5672:5672"

  redis:
    restart: unless-stopped
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/celery/Dockerfile
    depends_on:
      - rabbit
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_DATABASE=aggregator
      - POSTGRES_USER=aggregator_django
      - POSTGRES_PASSWORD=techdeck8800
      - POSTGRES_HOST=db
    links:
      - rabbit
      - redis
    extra_hosts:
      - "db:192.168.1.38"

  flower:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/flower/Dockerfile
    depends_on:
      - celery
      - rabbit
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - FLOWER_ADMIN=admin
      - FLOWER_PASSWORD=password
    links:
      - rabbit
      - redis