# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 19:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.CharField(max_length=1024, unique=True, validators=[django.core.validators.RegexValidator(message='slug valid error', regex='^[-_a-z\\d]+$')], verbose_name='Слаг')),
                ('url', models.CharField(editable=False, max_length=2048, unique=True, validators=[django.core.validators.RegexValidator(message='slug valid error', regex='^(($)|(([-_\\da-z]+/)+$))')], verbose_name='URL')),
                ('scoring', models.IntegerField(default=0, verbose_name='Скоринг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(verbose_name='Последнее изменение')),
                ('_title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('_meta_title', models.CharField(blank=True, max_length=256, verbose_name='Мета заголовок')),
                ('_meta_keywords', models.CharField(blank=True, max_length=256, verbose_name='Мета ключевые слова')),
                ('_meta_description', models.CharField(blank=True, max_length=256, verbose_name='Мета описание')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='shop.CategoryNode')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
