# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynode',
            name='order',
            field=models.IntegerField(default=0, verbose_name='порядок'),
        ),
    ]
