# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDescribable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestDisplayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=1024, unique=True, verbose_name='Слаг')),
                ('url', models.CharField(editable=False, max_length=2048, unique=True, verbose_name='URL')),
                ('scoring', models.IntegerField(default=0, verbose_name='Скоринг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestIndexable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('_meta_title', models.CharField(blank=True, max_length=256, verbose_name='Мета заголовок')),
                ('_meta_keywords', models.CharField(blank=True, max_length=256, verbose_name='Мета ключевые слова')),
                ('_meta_description', models.CharField(blank=True, max_length=256, verbose_name='Мета описание')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
                'abstract': False,
                'verbose_name': 'Страница',
            },
        ),
        migrations.CreateModel(
            name='TestNamed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTimeStamped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(verbose_name='Последнее изменение')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
