# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_for_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDisplayableGetUrlNotImplemented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=1024, unique=True, verbose_name='Слаг')),
                ('url', models.CharField(editable=False, max_length=2048, unique=True, verbose_name='URL')),
                ('scoring', models.IntegerField(default=0, verbose_name='Скоринг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
