# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_TestDisplayableGetUrlNotImplemented'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestDisplayableGetUrlNotImplemented',
            new_name='TestDisplayableNotImplemented',
        ),
    ]
