# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_rename model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.CharField(max_length=1024, unique=True, verbose_name='Слаг')),
                ('url', models.CharField(editable=False, max_length=2048, unique=True, verbose_name='URL')),
                ('scoring', models.IntegerField(default=0, verbose_name='Скоринг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(verbose_name='Последнее изменение')),
                ('_title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('_meta_title', models.CharField(blank=True, max_length=256, verbose_name='Мета заголовок')),
                ('_meta_keywords', models.CharField(blank=True, max_length=256, verbose_name='Мета ключевые слова')),
                ('_meta_description', models.CharField(blank=True, max_length=256, verbose_name='Мета описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
