# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_TestWebPage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('vendor', models.CharField(max_length=255, verbose_name='Производитель')),
                ('is_in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
                ('is_sale', models.BooleanField(default=False, editable=False, verbose_name='В распродаже')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Бестселлер')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestOfferPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.CharField(max_length=1024, unique=True, verbose_name='Слаг')),
                ('url', models.CharField(editable=False, max_length=2048, unique=True, verbose_name='URL')),
                ('scoring', models.IntegerField(default=0, verbose_name='Скоринг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(verbose_name='Последнее изменение')),
                ('_title', models.CharField(blank=True, max_length=256, verbose_name='Заголовок')),
                ('_meta_title', models.CharField(blank=True, max_length=256, verbose_name='Мета заголовок')),
                ('_meta_keywords', models.CharField(blank=True, max_length=256, verbose_name='Мета ключевые слова')),
                ('_meta_description', models.CharField(blank=True, max_length=256, verbose_name='Мета описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('vendor', models.CharField(max_length=255, verbose_name='Производитель')),
                ('is_in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
                ('is_sale', models.BooleanField(default=False, editable=False, verbose_name='В распродаже')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Бестселлер')),
            ],
            options={
                'verbose_name': 'Страница продукта',
                'verbose_name_plural': 'Страница продукта',
                'abstract': False,
            },
        ),
    ]
