# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_shop_old_price_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='testofferpage',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
